### ISSUE TITLE
Leakables forget what their material is!

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1131]
If the material is set to obsidian, the leakable will still complain if you try to place or break any block within the region, not only obsidian.

If you watched that match of "The Dojo", there was also the case that people were breaking non-core blocks within the core region and still getting touch credit.

**Comment by master00ofdsiware** [comment]
The same also happens with destroyables (monuments).

**Comment by AustinLMayes** [comment]
I've added an attribute to destroyables (monuments/leakables) called `enforce-anti-repair`. Which is as of now set to default to off. This attribute makes it so that if the objective is not repairable, a message will be sent to users who place blocks in the region, and Atlas will block then. If it is off (default) the blocks will be placed as normal. 

I've also fixed the issue with placing blocks in the areas around leakables.

**Comment by AustinLMayes** [comment]
Just to follow up on this. Since this does change gameplay, I've bumped the specification to `1.0.2`. Any map with a lower specification will default to enforcing the repair rules and cannot be overridden. 

Simply use a specification at or above `1.0.2` to use this feature.
