### ISSUE TITLE
Remove flint from Sandstorm

### ISSUE THREAD

**Issue by Aphelion-** [Avicus/Issues#364]
![Fire] (http://i.imgur.com/ZE63wBE.png)

If it isn't enabled, how could he set his own team on fire?

**Comment by ParaSpider** [comment]
There's gravel and iron, so...

**Comment by Aphelion-** [comment]
So you enabled the possibility of turning your own team on fire?

**Comment by ParaSpider** [comment]
It can be done, I suppose so but I don't see teamkilling frequently on this map. If there is, /report.

I can't say for sure whether this will be fixed or not since I have seen it used well against the enemy (and to burn skybridges) but time will tell if anyone decides if this should be changed or not.

**Comment by ParaSpider** [comment]
Any other maps with flint? I think I have an idea to prevent teamkilling

**Comment by ParaSpider** [comment]
Replaced with clay!
