### ISSUE TITLE
Hole in Forerunner CTH, players can get stuck in the hole

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#499]

**Comment by Tanpiku** [comment]
Coordinates? Picture?

**Comment by resepignev** [comment]
it's a dube of #418

**Comment by Tanpiku** [comment]
We added the decay flag though

**Comment by resepignev** [comment]
but it's still happening. Seems like the flag doesn't work...

**Comment by Tanpiku** [comment]
It does, we tested it. Are leaves decaying or do you have the actual location of the hole? If there's no pictures or coordinates, I'm closing this.

**Comment by resepignev** [comment]
![2015-04-26_01 10 33](https://cloud.githubusercontent.com/assets/8640683/7335225/43e48a56-ebb1-11e4-8dfc-7a2ed0b8d29b.png)
![2015-04-26_01 10 37](https://cloud.githubusercontent.com/assets/8640683/7335228/440d7966-ebb1-11e4-9a64-481a07c7bc95.png)
![2015-04-26_01 10 47](https://cloud.githubusercontent.com/assets/8640683/7335227/43ff08ea-ebb1-11e4-8f73-ff0e9667b2c1.png)
![2015-04-26_01 10 59](https://cloud.githubusercontent.com/assets/8640683/7335229/441ad3f4-ebb1-11e4-9456-3c946747e5a5.png)
![2015-04-26_01 11 26](https://cloud.githubusercontent.com/assets/8640683/7335226/43f1d2b0-ebb1-11e4-9920-ac1368e62c7e.png)
There ya go!
Btw the server restarted a few times after the other issue was closed.

**Comment by Tanpiku** [comment]
The decay flag worked flawlessly on dev server. Something happened somewhere along the line I guess unless the leaves were already decayed in the first place when we added it.

Due to Forerunner being impossible to ever edit again due to world corruption or lag, there's not much we can do. If you get actual video of the leaves decaying on that map during the match, then make a new issue saying the flag doesn't work.

**Comment by resepignev** [comment]
okay, I'll try to get a vid.
