### ISSUE TITLE
World Height Glitch

### ISSUE THREAD

**Issue by Straightened** [Avicus/Issues#517]
If you're at the height limit on a bridge and you jump, you simply get teleported to the ground below. Here's a video for an example.

https://www.youtube.com/watch?v=tpM-_wNrx3s

**Comment by resepignev** [comment]
Well, the region flag "enter" works like this (I guess). You try to enter a region, but you get teleported back from where you came. Since you jump forward and up, the plugin thinks you jumped from the ground into the region, so it teleports you back to the ground.
It can be easily fixed, if you remove the "enter" flag from the "boundary" region.

**Comment by Tanpiku** [comment]
I'd prefer to keep the enter flag so you are in range of the map, and so you don't icarus across the entire map away to a monument or something or to be too unpredictable.

**Comment by KyloCode** [comment]
It was intended to resolve the issue where you can jump in to an enter region and just hover. Resolved, once servers restart.
